# action.yml
name: 'Linux Builder'
description: 'Helper action to build in a specific Docker container'
inputs:
  build-type:
    description: 'Build type'
    required: true
    default: 'plugin' # or 'library'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build-type }}
