name: iOS CI
on: [push, workflow_dispatch]

env:
  QT_VERSION: 5.15.2

jobs:
  build-engine:
    name: "Build maplibre-gl-native"
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source
          submodules: recursive
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          target: ios

      - name: Build maplibre-gl-native
        run: |
          mkdir build && cd build
          cmake ../source/dependencies/maplibre-gl-native/ \
            -DCMAKE_TOOLCHAIN_FILE=../source/dependencies/maplibre-gl-native/platform/ios/platform/ios/toolchain.cmake \
            -G Xcode \
            -DPLATFORM=OS64COMBINED \
            -DDEPLOYMENT_TARGET=12.0 \
            -DENABLE_BITCODE=ON \
            -DMBGL_WITH_QT=ON \
            -DMBGL_WITH_WERROR=OFF \
            -DMBGL_QT_LIBRARY_ONLY=ON \
            -DMBGL_QT_STATIC=ON \
            -DMBGL_QT_WITH_INTERNAL_SQLITE=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../install-gl
          cmake --build . --config Release
          cmake --install . --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: maplibre-gl-native_iOS
          path: install-gl

  build-plugin:
    name: "Build qt-geoservices-maplibre"
    runs-on: macos-latest
    needs: build-engine

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          target: ios
      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: maplibre-gl-native_iOS
          path: install-gl

      - name: Build qt-geoservices-maplibre
        run: |
          mkdir build && cd build
          qmake ../source/ MBGL_PATH=../install-gl
          make -j2
          INSTALL_ROOT=../install make install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qt-geoservices-maplibre_iOS
          path: install/Users/runner/work/qt-geoservices-maplibre/Qt/${{ env.QT_VERSION }}/ios
